name:
  chinese: 傳統沖繩剛柔流空手道連盟 東恩納空手道場 台灣支部
  japanese: 伝統沖縄剛柔流空手道連盟 東恩納空手道場 台灣支部
  english: Traditional Okinawa Goju Ryu Karate Do Federation(TOGKF) Higaonna Dojo Taiwan Branch
  dojo: 台北大同道場
location: 台北市大同區區
email: togkf.tw@gmail.com
slogan: 鏈結台灣與沖繩、鍛鍊正統沖繩剛柔流空手道。
social:
  facebook: https://www.facebook.com/OkinawaGojuRyuKaratedoHigaonnaDojo.tw
  instagram: https://www.instagram.com/higaonnadojo.tw/
  line: https://linevoom.line.me/user/_daVP5h-2JnZ5cOrX8SgbU7jY09X2B2tDzO2g6qE
external:
  blogger: https://sanchintw.blogspot.com
address:
  name: 台北市大同區雙連
  map: https://www.google.com/maps/place/%E9%9B%99%E9%80%A3/@25.0577124,121.5189301,18z/data=!4m15!1m8!3m7!1s0x3442a95a412a38c3:0x99cb386438d02546!2zMTA0OTHlj7DljJfluILkuK3lsbHljYDovrLlronooZc!3b1!8m2!3d25.0648387!4d121.5298306!16s%2Fg%2F1tkb2tgr!3m5!1s0x3442a969e2b79ca5:0xa7975fe4f6194426!8m2!3d25.0577788!4d121.5206671!16s%2Fm%2F03cy_59?entry=ttu&g_ep=EgoyMDI1MDgxOS4wIKXMDSoASAFQAw%3D%3D
  map_embed: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d28914.32027991668!2d121.519801!3d25.058157!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a941ff94b3c7%3A0xe6ad0cbc5567d788!2zMTAz5Y-w5YyX5biC5aSn5ZCM5Y2A6ZuZ6YCj!5e0!3m2!1szh-TW!2stw!4v1756197512566!5m2!1szh-TW!2stw" 
schedule:
  day1: 週二
  time1: 20:00~22:00(自主)
  day2: 週四
  time2: 20:00~22:00
  day3: 週六
  time3: 14:00~17:00
